# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

variables:
  - group: coverity-cli
  - group: coverity-bd-scan

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  displayName: "Coverity CLI Scan"
  inputs:
    targetType: 'inline'
    script: 'coverity scan -o commit.connect.url=$(COVERITY_URL)'

- task: BlackDuckSecurityScan@2
  displayName: "BD Security Scan Plugin - Coverity Scan"
  inputs:
    scanType: 'coverity'
    coverityUrl: $(COVERITY_URL)
    coverityUser: $(COV_USER)
    coverityUserPassword: $(COVERITY_PASSPHRASE)
    coverityInstallDirectory: 'C:\Program Files\Coverity\Coverity Static Analysis 2024.9.1'
    coverityLocal: true
    coverityProjectName: 'juice-shop'
    coverityStreamName: 'juice-shop-master'

