# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

variables:
- group: polaris-variables

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'polaris'
    polarisServerUrl: $(POLARIS_SERVER_URL)
    polarisAccessToken: 's4jpgckfat47f3dcaebrc486ljgdueq6h1hkr3kc7vtdta5rjo176u1b6u17ahuh78onjns5bdjs4'
    polarisAssessmentTypes: 'SAST,SCA'
    polarisTestScaType: 'SCA-SIGNATURE'
  displayName: Polaris Scan