name: "Polaris scan"

on:
  workflow_call:
    secrets:
      polaris_access_token:
        description: "Access token for Polaris (Synpsys)"
        required: true   
jobs:
  build:
    name: code scan with Polaris
    runs-on: ubuntu-latest
    timeout-minutes: 150    
    steps:
    # Checks out application code
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Polaris Static Analysis
      run: |
          export POLARIS_ACCESS_TOKEN=${{ secrets.polaris_access_token }}
          wget -q https://csprod.polaris.synopsys.com/api/tools/polaris_cli-linux64.zip
          unzip -j -o polaris_cli-linux64.zip -d ${{ github.workspace }}/tmp
          ${{ github.workspace }}/tmp/polaris analyze -w 
          
  
