name: polaris-ss-action
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch: 
jobs:
  build:
    name: code scan with Polaris
    runs-on: ubuntu-latest
    timeout-minutes: 150    
    steps:
    # Checks out application code
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Polaris Scan
      uses: blackduck-inc/black-duck-security-scan@v2.0.0
      with:
        polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
        polaris_assessment_types: 'SAST'
        polaris_application_name: tenjupaulGH-${{ github.event.repository.name }}
        polaris_project_name: tenjupaulGH-${{ github.event.repository.name }}
        # include_diagnostics: true
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
#        include-hidden-files: true

